version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-dogs-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dogs_db
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  dogs_microservice:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: dogs-microservice
    ports:
      - "5000:5000"
    volumes:
      - ./DB:/app
      - ./images:/app/images
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=dogs_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      retries: 5

  streamlit_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./images:/app/images

volumes:
  mysql_data:
