version: '3.8'

services:
  db:
    container_name: mysql-dogs-db
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dogs_db
    ports:
      - "3307:3306"
    volumes:
      - /images
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p", "password"]
      retries: 2
      timeout: 5s


  dogs_microservice:
    container_name: dogs_microservice
    build:
      context: ./Flask
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    networks:
      - my_network

  streamlit_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  dogs_db:
