version: '3.9'

services:
  db:
    container_name: mysql-dogs-db
    build: 
      context: /DB
      dockerfile: dockerfile
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dogs_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  dogs_microservice:
    container_name: dogs_microservice
    build:
      context: ./Flask
      dockerfile: Dockerfile
    depends_on:
      - "db"
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    networks:
      - my_network


  streamlit_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
