version: '3.9'

services:
  db:
    container_name: mysql-dogs-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dogs_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -p$password"]
      retries: 2
      timeout: 5s

  dogs_microservice:
    container_name: dogs_microservice
    build:
      context: ./Flask
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    networks:
      - my_network


  streamlit_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
